import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";

import "./globals.css";

const EBGaramond = EB_Garamond({
    variable: "--font-eb-garamond",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={EBGaramond.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
